services:
  api:
    build:
      context: ./api
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - '/bin'
      - '/obj'
    depends_on:
      - db
  
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - WATCHPACK_POLLING=true
    volumes:
      - ./front:/app
      - "/app/node_modules"
      - "/app/src/proto/generated"
    depends_on:
      - proxy
  
  proxy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - api
  
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=testDb
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
    ports:
      - 5432:5432