services:
  api:
    build:
      context: ./api
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - '/bin'
      - '/obj'
    depends_on:
      - db
  
  consumer:
    build:
      context: ./consumer
    ports:
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050
    volumes:
      - '/bin'
      - '/obj'
    depends_on:
      - mongo
      - kafka
      - rabbit
  
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - WATCHPACK_POLLING=true
    volumes:
      - ./front:/app
      - "/app/node_modules"
      - "/app/src/proto/generated"
    depends_on:
      - proxy
  
  proxy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - api
  
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=testDb
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
    ports:
      - 5432:5432
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  
  mybook:
    build:
      context: ./MyBook
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5100
    ports:
      - 5100:5100
    depends_on:
      - db
      - rabbit
